version: "3"

services:
  db:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
  server:
    build: ./
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=password
      - DB_DIALECT=postgres
      - DB_NAME_TEST=postgres
      - DB_NAME_DEVELOPMENT=postgres
      - DB_NAME_PRODUCTION=postgres
      - JWTKEY='fvdlvndsf.4lvds33fkvmdsflvmlvsdfvmkd'
      - TOKEN_EXPIRATION=48h
      - BEARER=Bearer
      - PORT=3000
    command: sh -c "npm run start:prod"